pub_hdrs = {hxx ixx txx}{**}

./: $pub_hdrs

# Install into the bx/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/bx/
  install.subdirs = true
}
