# Static libs: see ../common/buildfile (auto-symexport data caveat on MSVC).
#
import libs = libbgfx%liba{bgfx}
import libs += libbimg%liba{bimg}
import libs += libbx%liba{bx}

include ../common/

# Embedded shaders (*.bin.h). No external runtime bins.
#
exe{metaballs}: \
  {hxx cxx}{**} \
  file{vs_metaballs.bin.h fs_metaballs.bin.h} \
  ../common/libue{example-common} \
  $libs
{
  test = false

  cxx.poptions =+ \
    "-I$out_base" "-I$src_base" \
    "-I$src_root/common" \
    "-I$src_root/common/3rdparty" \
    -DENTRY_CONFIG_IMPLEMENT_MAIN=1 \
    -DUSE_ENTRY=1
}

exe{metaballs}: file{vs_metaballs.bin.h fs_metaballs.bin.h}: include = adhoc
exe{metaballs}: ../common/hxx{common args bgfx_utils}: include = adhoc
