intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libbimg%lib{bimg}
import impl_libs += liblodepng%lib{lodepng} \
                    stb_image%lib{stb_image} \
                    libtinyexr%lib{tinyexr} \
                    libsimplewebp%lib{simplewebp}

# Public headers.
#
pub = [dir_path] ../include/bimg/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

# Automatic DLL symbol exporting (bdep new auto-symexport pattern).
#
lib{bimg-decode}: libul{bimg-decode}: $pub/{$pub_hdrs}

# Decode implementation and private headers.
#
libul{bimg-decode}: {hxx cxx}{**} $impl_libs $intf_libs

libs{bimg-decode}: def{bimg-decode}: include = ($cxx.target.system == 'win32-msvc')
def{bimg-decode}: libul{bimg-decode}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

cxx.poptions += -DBIMG_CONFIG_PARSE_AVIF=0

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{bimg-decode}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                        "-I$out_pfx_inc/bimg" "-I$src_pfx_inc/bimg"
  cxx.export.libs = $intf_libs
  cxx.pkgconfig.include = include/ include/bimg/
}

if $version.pre_release
  lib{bimg-decode}: bin.lib.version = "-$version.project_id"
else
  lib{bimg-decode}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
