# Static libs: see ../common/buildfile (auto-symexport data caveat on MSVC).
#
import libs = libbgfx%liba{bgfx}
import libs += libbimg%liba{bimg}
import libs += libbx%liba{bx}

include ../common/

exe{helloworld}: \
  c{helloworld} \
  ../common/libue{example-common} \
  $libs
{
  test = false

  c.poptions =+ \
    "-I$out_base" "-I$src_base" \
    "-I$src_root/common" \
    -DENTRY_CONFIG_IMPLEMENT_MAIN=1 \
    -DUSE_ENTRY=1
}

# Extra example sources stay in git. Target-specific dist so collect()
# drops them even if dist_include rewrites include=false to adhoc.
#
{hxx cxx c file}{*}:
{
  dist = false
}
