# Static libs: see ../common/buildfile (auto-symexport data caveat on MSVC).
#
import libs = libbgfx%liba{bgfx}
import libs += libbimg%liba{bimg}
import libs += libbx%liba{bx}

include ../common/

exe{drawstress}: \
  {hxx cxx}{**} \
  file{*.bin.h} \
  ../common/libue{example-common} \
  $libs
{
  test = false

  cxx.poptions =+ \
    "-I$out_base" "-I$src_base" \
    "-I$src_root/common" \
    -DENTRY_CONFIG_IMPLEMENT_MAIN=1 \
    -DUSE_ENTRY=1
}

exe{drawstress}: file{*.bin.h}: include = adhoc
exe{drawstress}: ../common/hxx{common args bgfx_utils}: include = adhoc
