# Static libs: public bx inlines reference global data (for example
# Ticks::s_kInvFreq) that Windows DLL auto-import does not cover.
#
libs =
import libs += libbimg-decode%liba{bimg-decode}
import libs += libbimg-encode%liba{bimg-encode}
import libs += libbimg%liba{bimg}
import libs += libbx%liba{bx}

exe{texturec}: {hxx ixx txx cxx}{**} $libs testscript

out_pfx = [dir_path] $out_root/tools/
src_pfx = [dir_path] $src_root/tools/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
