# Static libs: see ../common/buildfile (auto-symexport data caveat on MSVC).
#
import libs = libbgfx%liba{bgfx}
import libs += libbimg%liba{bimg}
import libs += libbx%liba{bx}

include ../common/

# Executable named after the primary source (helloworld.cpp).
#
exe{helloworld}: {hxx cxx}{**} ../common/libue{example-common} $libs
{
  test = false

  cxx.poptions =+ \
    "-I$out_base" "-I$src_base" \
    "-I$src_root/common" \
    -DENTRY_CONFIG_IMPLEMENT_MAIN=1 \
    -DUSE_ENTRY=1
}

exe{helloworld}: ../common/hxx{common args bgfx_utils}: include = adhoc

# helloworld.cpp includes common.h, which pulls in bx/macros.h and entry/dbg.h.
# Same per-TU suppression as common/buildfile.
#
if ($cxx.id.type == 'clang')
  obj{helloworld}: cxx.coptions += -Wno-gnu-zero-variadic-macro-arguments
