import libs = libbgfx%lib{bgfx}
import libs += libbimg%lib{bimg}

include ../common/

# Executable named after the primary source (helloworld.cpp).
#
exe{helloworld}: {hxx cxx}{**} ../common/libue{example-common} $libs
{
  test = false

  cxx.poptions =+ \
    "-I$out_base" "-I$src_base" \
    "-I$src_root/common" \
    "-I$src_root/common/3rdparty" \
    -DENTRY_CONFIG_IMPLEMENT_MAIN=1 \
    -DUSE_ENTRY=1
}

exe{helloworld}: ../common/hxx{common args bgfx_utils}: include = adhoc
