intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# Public headers (bx/, tinystl/, compat/).
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

# Automatic DLL symbol exporting (bdep new auto-symexport pattern).
#
lib{bx}: libul{bx}: $pub/{$pub_hdrs}

# Sources (exclude amalgamated single-TU build).
#
libul{bx}: cxx{** -amalgamated} $impl_libs $intf_libs

libs{bx}: def{bx}: include = ($cxx.target.system == 'win32-msvc')
def{bx}: libul{bx}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_inc" "-I$src_pfx_inc"

# Platform compatibility headers (also exported to consumers).
#
compat_inc = [dir_path]
if ($cxx.target.class == 'windows')
{
  if ($cxx.target.system == 'mingw32')
    compat_inc = [dir_path] $src_pfx_inc/compat/mingw/
  else
    compat_inc = [dir_path] $src_pfx_inc/compat/msvc/
}
elif ($cxx.target.class == 'macos')
  compat_inc = [dir_path] $src_pfx_inc/compat/osx/
elif ($cxx.target.class == 'linux')
  compat_inc = [dir_path] $src_pfx_inc/compat/linux/
elif ($cxx.target.class == 'bsd')
  compat_inc = [dir_path] $src_pfx_inc/compat/freebsd/

if ($compat_inc != [dir_path])
  cxx.poptions =+ "-I$compat_inc"

# Required by every translation unit and by public headers.
#
if $config.libbx.debug
  debug_def = -DBX_CONFIG_DEBUG=1
else
  debug_def = -DBX_CONFIG_DEBUG=0

cxx.poptions += $debug_def

# System libraries / frameworks (not importable targets: use *.libs).
# Prefer -pthread over -lpthread (HOWTO/link-pthread). -ldl for bx::dlopen
# on non-Apple *nix. Apple folds both into libSystem.
#
if ($cxx.target.system != 'win32-msvc')
  sys_libs = -pthread
else
  sys_libs = [null]

if ($cxx.target.class == 'macos')
  sys_libs += -framework Foundation -framework CoreFoundation
elif ($cxx.target.class != 'windows')
  sys_libs += -ldl

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{bx}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" $debug_def
  cxx.export.libs = $intf_libs
}

if ($compat_inc != [dir_path])
  lib{bx}: cxx.export.poptions =+ "-I$compat_inc"

if ($sys_libs != [null])
{
  cxx.libs += $sys_libs
  lib{bx}: cxx.export.libs += $sys_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{bx}: bin.lib.version = "-$version.project_id"
else
  lib{bx}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers (none under src/, but keep the rule).
#
{hxx ixx txx}{*}: install = false
