pub_hdrs = {hxx ixx txx}{**}

./: $pub_hdrs

# Install into the bgfx/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/bgfx/
  install.subdirs = true
}
