libs =
#import libs += libhello%lib{hello}

exe{bgfx-shaderc}: {hxx ixx txx cxx}{**} $libs testscript

out_pfx = [dir_path] $out_root/tools/
src_pfx = [dir_path] $src_root/tools/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
