intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libbx%lib{bx}
import impl_libs += libbimg%lib{bimg}

# Vulkan is loaded at runtime via dlopen (libMoltenVK.dylib / libvulkan.so.1 /
# vulkan-1.dll). Headers come from upstream 3rdparty/khronos/vulkan-local
# (cppget Vulkan-Headers 1.3.216 is older than this bgfx pin requires).

# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{bgfx}: $pub/{$pub_hdrs}

# Implementation sources. Exclude amalgamated TU. Platform backends that are
# disabled via BGFX_CONFIG_* still compile to empty TUs (ifdef guards).
#
# On macOS, renderer_vk.cpp is compiled as renderer_vk.mm (Objective-C++ for
# Cocoa/Metal surface interop). Elsewhere the plain .cpp is used.
#
if ($cxx.target.class == 'macos')
  lib{bgfx}: {hxx cxx}{** -amalgamated -renderer_vk -3rdparty/** -vulkan-local/**} \
             mm{renderer_vk} \
             $impl_libs $intf_libs
else
  lib{bgfx}: {hxx cxx}{** -amalgamated -3rdparty/** -vulkan-local/**} \
             $impl_libs $intf_libs

# Embedded shader binaries and shader sources are included from C++ headers.
#
lib{bgfx}: file{**.bin.h}: include = adhoc
lib{bgfx}: file{**.sc}: include = adhoc
lib{bgfx}: file{**.sh}: include = adhoc
lib{bgfx}: file{**.idl.inl}: include = adhoc

# RenderDoc, h264, and vulkan-local thunks (not installed).
#
lib{bgfx}: 3rdparty/renderdoc/hxx{renderdoc_app}: include = adhoc
lib{bgfx}: 3rdparty/h264/hxx{h264}: include = adhoc
lib{bgfx}: 3rdparty/metal-cpp/file{**}: include = adhoc
lib{bgfx}: vulkan-local/hxx{**}: include = adhoc

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                "-I$src_pfx_src/3rdparty"

# Desktop backends: Vulkan everywhere, Metal on Apple. Defining any
# BGFX_CONFIG_RENDERER_* skips the platform-default block in config.h.
#
metal = ($cxx.target.class == 'macos' ? 1 : 0)

cxx.poptions += \
  -DBGFX_CONFIG_RENDERER_VULKAN=1 \
  -DBGFX_CONFIG_RENDERER_DIRECT3D11=0 \
  -DBGFX_CONFIG_RENDERER_DIRECT3D12=0 \
  "-DBGFX_CONFIG_RENDERER_METAL=$metal" \
  -DBGFX_CONFIG_RENDERER_OPENGL=0 \
  -DBGFX_CONFIG_RENDERER_OPENGLES=0 \
  -DBGFX_CONFIG_RENDERER_WEBGPU=0 \
  -DBGFX_CONFIG_RENDERER_GNM=0 \
  -DBGFX_CONFIG_RENDERER_AGC=0 \
  -DBGFX_CONFIG_RENDERER_NVN=0 \
  -DBGFX_CONFIG_VIDEO=0

# Platform system libraries (not importable targets: use *.libs).
# Vulkan is dlopen'd at runtime. pthread/dl come from libbx export.
#
if ($cxx.target.class == 'macos')
{
  # Cocoa/Metal/IOKit: Metal backend and MoltenVK surface interop.
  #
  sys_libs = \
    -framework Cocoa \
    -framework Metal \
    -framework MetalKit \
    -framework QuartzCore \
    -framework IOKit
}
elif ($cxx.target.class == 'windows')
{
  if ($cxx.target.system == 'mingw32')
    sys_libs = -luser32 -lgdi32
  else
    sys_libs = user32.lib gdi32.lib
}
else
  sys_libs = [null]

# Export options. libbx is an interface dependency (AllocatorI, embedded
# shader helpers). Export platform libs for shared-library consumers.
#
lib{bgfx}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

if ($sys_libs != [null])
{
  cxx.libs += $sys_libs
  lib{bgfx}: cxx.export.libs += $sys_libs
}

if $version.pre_release
  lib{bgfx}: bin.lib.version = "-$version.project_id"
else
  lib{bgfx}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
