intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libbx%lib{bx}
import impl_libs += libastcenc%lib{astcenc}

# Public headers.
#
pub = [dir_path] ../include/bimg/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

# Automatic DLL symbol exporting (bdep new auto-symexport pattern).
#
lib{bimg}: libul{bimg}: $pub/{$pub_hdrs}

# Core image implementation + private headers.
#
libul{bimg}: {hxx cxx}{**} $impl_libs $intf_libs

libs{bimg}: def{bimg}: include = ($cxx.target.system == 'win32-msvc')
def{bimg}: libul{bimg}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options (bimg is not in public headers of consumers of libbgfx as
# interface, but libbimg consumers need bimg headers + libbx).
#
lib{bimg}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                        "-I$out_pfx_inc/bimg" "-I$src_pfx_inc/bimg"
  cxx.export.libs = $intf_libs
  cxx.pkgconfig.include = include/ include/bimg/
}

if $version.pre_release
  lib{bimg}: bin.lib.version = "-$version.project_id"
else
  lib{bimg}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
