intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libbx%lib{bx}

# Public headers.
#
pub = [dir_path] ../include/bimg/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{bimg}: $pub/{$pub_hdrs}

# Core image implementation + private headers + astc-encoder.
#
lib{bimg}: {hxx cxx}{** -3rdparty/**} \
           3rdparty/astc-encoder/source/cxx{**} \
           $impl_libs $intf_libs

# Private headers under 3rdparty (astc) and src.
#
lib{bimg}: 3rdparty/astc-encoder/source/hxx{**}: include = adhoc
lib{bimg}: 3rdparty/astc-encoder/include/hxx{**}: include = adhoc

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/
astc_inc    = [dir_path] $src_pfx_src/3rdparty/astc-encoder/include/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                "-I$astc_inc"

# Match upstream genie defines for astc-encoder.
#
cxx.poptions += -DASTCENC_F16C=0 -DASTCENC_NEON=0

# Export options (bimg is not in public headers of consumers of libbgfx as
# interface, but libbimg consumers need bimg headers + libbx).
#
lib{bimg}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                        "-I$out_pfx_inc/bimg" "-I$src_pfx_inc/bimg"
  cxx.export.libs = $intf_libs
  cxx.pkgconfig.include = include/ include/bimg/
}

if $version.pre_release
  lib{bimg}: bin.lib.version = "-$version.project_id"
else
  lib{bimg}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
