intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libbx%lib{bx}

# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

# Automatic DLL symbol exporting (bdep new auto-symexport pattern).
#
lib{bimg}: libul{bimg}: $pub/{$pub_hdrs}

# Core image implementation + private headers + astc-encoder.
#
libul{bimg}: {hxx cxx}{** -3rdparty/**} \
             3rdparty/astc-encoder/source/cxx{**} \
             $impl_libs $intf_libs

# Private headers under 3rdparty (astc) and src.
#
libul{bimg}: 3rdparty/astc-encoder/source/hxx{**}: include = adhoc
libul{bimg}: 3rdparty/astc-encoder/include/hxx{**}: include = adhoc

libs{bimg}: def{bimg}: include = ($cxx.target.system == 'win32-msvc')
def{bimg}: libul{bimg}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/
astc_inc    = [dir_path] $src_pfx_src/3rdparty/astc-encoder/include/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                "-I$astc_inc"

# Match upstream genie defines for astc-encoder.
#
cxx.poptions += -DASTCENC_F16C=0 -DASTCENC_NEON=0

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options (bimg is not in public headers of consumers of libbgfx as
# interface, but libbimg consumers need bimg headers + libbx).
#
lib{bimg}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

if $version.pre_release
  lib{bimg}: bin.lib.version = "-$version.project_id"
else
  lib{bimg}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
